### ISSUE TITLE
Support for POST/PATCH/DELETE/etc. methods?

### ISSUE THREAD

**Issue by tonycpsu** [thorrr/YahooSports#1]
Hi, I was wondering if you were considering adding support for non-GET HTTP methods for things like roster updates, transactions, etc.  I have my own homegrown API that supports these, but it uses OAuth1, and there's been an outage of the API for OAuth1 clients for almost a week now.

This module has been very valuable for re-establishing read-only API support in my application, but it'd be great if it supported other HTTP methods.  This should just involve proxying the other HTTP methods through to the Oauth[12]Session object.

If this isn't something you'll be adding, I can try to put together a PR.

**Comment by thorrr** [comment]
Great!  Glad this library is working for you.  The Oauth1 stuff stopped working for me about a month ago so that was painful.  But as a bonus I got the "auto-refresh" stuff working so I don't have to re-authenticate every hour.

I'd love a PR - I haven't gotten around to doing the POST stuff yet.

**Comment by thorrr** [comment]
closed with #2
