### ISSUE TITLE
Losing saved session

### ISSUE THREAD

**Issue by mattorlove** [thorrr/YahooSports#5]
First, thanks for this! Been very helpful for me :D

I have a cron that runs every 5 minutes, uses the stored auth session file, and grabs data. After some time of running this the previously authenticated session stops working and I need to re-authorize permissions. Any idea what may be going on? Is there a limited duration on the authenticated session? If so, is there any way to extend that?

Thanks again!

**Comment by thorrr** [comment]
Thank you for the kind words.

It sounds like you may not be using the "refresh token" that's stored in the `Yahoo_Connection` object.  You should be able to do something like:

 ```python
    if not session.is_live_session():
        try:
            session.refresh_session()
        except NoRefreshToken:
            # session hasn't been initiated so there's no refresh token stored yet
            pass
```
before your functions that call `session.get()`

If that doesn't work, let me know and I'll put logging everywhere.  This code is pretty messy and probably needs to be rewritten.

**Comment by mattorlove** [comment]
Ahh, that did it! Thanks so much, appreciate the quick reply!
